{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    # Add any specific labels for the namespace if needed
    {{- include "chart.labels" . | nindent 4 }}
{{- end }} 