name = "keboola-test-mcp"
main = "src/index.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]
account_id = "b60618d22bd084a130391a0a358008d7"

# Define routes for your Worker
# routes = [
#   { pattern = "mcp.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

[vars]
# Environment variables here will be available at build time
# Runtime variables should be set using `wrangler secret put`

# Configure your CORS settings as needed
ALLOWED_ORIGINS = "*"
DEBUG = false

# Default variables (these will be overridden by secrets)
MCP_SERVER_URL = "https://mcp.canary-orion.keboola.dev"
KEBOOLA_API_URL = "https://connection.keboola.com"

# Workers settings
workers_dev = true
send_metrics = false

[build]

[env.production]
# Production-specific configuration 