name: Release Docker Image

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.2.3

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to Docker Hub

    env:
      # DockerHub login
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      # Proxy image
      IMAGE_NAME: "keboola/mcp-server"
      IMAGE_TAG: ${{ github.ref_name }} # Use the tag name as the image tag

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx # Assign an id to refer to outputs

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Explicitly specify the Dockerfile path
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64 # Example platforms, adjust if needed
          builder: ${{ steps.buildx.outputs.name }} # Use the Buildx builder instance 